Code improvements
hinoyso/Fylo-Project pull request #1
Opened 2024-03-21 18:21 UTC by hinoyso

Refactoring and enhancing codebase based on mentor feedback to improve readability, efficiency, and maintainability.

2024-03-24 17:32 UTC, danielmargolin commented
Overall looks great!
Left some small comments
Please fix them before merging

2024-03-24 17:32 UTC, danielmargolin requested changes

2024-03-24 17:32 UTC, danielmargolin commented on script.js
> +const totalSizeLimit = 15;
What is 15? 15 what? MB? KB? GB?
Consider switching to bytes and converting to MB only when you update the DOM

2024-03-24 17:32 UTC, danielmargolin commented on script.js
> +const calculateRemainingStorage = () => totalSizeLimit - (totalUploadedSize / MB);
If you don't read from localStorage, why do you need this logic? `totalUploadedSize` will always be 0, no?

2024-03-24 17:32 UTC, danielmargolin commented on script.js
> +      if (fileSize / MB > remainingStorage) {
Consider switching to positive approach:
```
if (fileSize / MB < remainingStorage) {
      totalUploadedSize += fileSize;
        
      } else {
alert("There is not enough space on the disk for file: " + fileName);
}

```

2024-03-24 17:32 UTC, danielmargolin approved these changes

2024-03-25 15:20 UTC, hinoyso commented
Hi Daniel,

I've made the necessary changes to address the issues you pointed out. The code has been updated according to your feedback.

Thank you for your valuable comments!

2024-03-25 15:21 UTC, merged